### ISSUE TITLE
directory is not found

### ISSUE THREAD

**Issue by abhi8422** [r0adkll/sign-android-release#15]
##[error]ENOENT: no such file or directory, scandir 'app/build/outputs/apk/release'

**Comment by r0adkll** [comment]
Could you please post your workflow YAML configuration? (or at least the signing portion of it)

**Comment by abhi8422** [comment]
name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
         signingKeyBase64: ${{ secrets.SIGNING_KEY }}
         alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
       keyPassword: ${{ secrets.KEY_PASSWORD }}

Pushing it on the master branch.

**Comment by r0adkll** [comment]
Okay so here:

```shell
bash ./gradlew assembleDebug --stacktrace
```

you are building the `debug` variant of your application (which, btw, you should be able to just call `./gradlew assembleDebug --stacktrace` without the `bash` command, hence why the `./` is there)

And in your signing configuration, you are specifying the **/release** folder for your apk outputs which is why the action can't find any apks. What you _should_ be doing is running `./gradlew assembleRelease` to assemble the release build of your app. This means you'll have to update your upload-artifact action as well to point to the release build too.

**Comment by abhi8422** [comment]
- name: Assemble Release Bundle
        run: |
          ./gradlew bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

Working now. Thank You.

**Comment by abhi8422** [comment]
The action is working fine but in artefacts, it's giving me three .apk files

1. app-release-unsigned-aligned.apk
2. app-release-unsigned-signed.apk(this is the only one which is signed)
3. app-release-unsigned.apk

Workflow code->
 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: ./gradlew build
      - name: Assemble Release Bundle
        run: |
          ./gradlew assembleRelease
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/release

**Comment by r0adkll** [comment]
Yes, I should probably have the action clean up it's "mess". This action generates the `-aligned.apk` when it zipaligns the APK, and then generates the `-signed.apk` version when it actually signs it. I'm going to close this issue and open a new one to remind me to do so

**Comment by bishwajeetbiswas** [comment]
Hi @r0adkll 

<img width="662" alt="Screenshot 2021-09-30 at 3 36 11 PM" src="https://user-images.githubusercontent.com/18626653/135436203-2a636957-241a-41a3-a84a-356363d3f8e9.png">
