### ISSUE TITLE
Warning about `set-env` command deprecated

### ISSUE THREAD

**Issue by lukas1** [r0adkll/sign-android-release#23]
Hi, recently I started getting this warning on my build step that uses this action (no other step in my workflow reports this warning)

```
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by lukas1** [comment]
Ok, I suppose this PR is supposed to fix that, right?

https://github.com/r0adkll/sign-android-release/pull/21

**Comment by r0adkll** [comment]
@lukas1 Yes! This should be resolved now

**Comment by davwheat** [comment]
@r0adkll Just hit this warning on my run a few mins ago. **This will be disabled on November 16th.**

**Comment by r0adkll** [comment]
Hmmm, interesting. I was pretty sure I updated the dependency to resolve this, let me check again
