### ISSUE TITLE
Any reason to commit /node_modules?

### ISSUE THREAD

**Issue by lhache** [r0adkll/sign-android-release#28]
Wondering if there is any reason to commit /node_modules?
If there is none, I can take care of that, let me know.

**Comment by r0adkll** [comment]
Yes, as described in the GitHub Actions docs: https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

>From your terminal, commit your action.yml, index.js, node_modules, package.json, package-lock.json, and README.md files. If you added a .gitignore file that lists node_modules, you'll need to remove that line to commit the node_modules directory.

They do list one alternative (but I don't feel it's worth the effort with the small size of this proj):

>As an alternative to checking in your node_modules directory you can use a tool called @vercel/ncc to compile your code and modules into one file used for distribution.

This is so the action is pre-built and can just be cloned and ran in your workflow.
