### ISSUE TITLE
Abandoned project, any alternative?

### ISSUE THREAD

**Issue by banool** [r0adkll/sign-android-release#66]
Does anyone know an alternative to this? It doesn't seem to work anymore a la https://github.com/r0adkll/sign-android-release/issues/63.

**Comment by ilharp** [comment]
+1. I'm planning to fork and maintain one if there's no other actively maintained version.

**Comment by ilharp** [comment]
And here it is.

[ilharp/sign-android-release](https://github.com/ilharp/sign-android-release)

※ Notice that it's likely to have many bugs since it's a new codebase. Bugfix will start in the next few days.

**Comment by vladimirevstratov** [comment]
Yeah, it will be nice this project to continue.

**Comment by Paso** [comment]
Can @r0adkll confirm that this project is abandoned or will it be fixed before it stops working?

**Comment by boswelja** [comment]
They aren't typically active on GH much nowadays. If/when they respond, we should discuss adding another maintainer or archiving

**Comment by r0adkll** [comment]
Ah, yes. Sorry for not being responsive here. Unfortunately I just don't have the time these days to maintain many projects in my free time so unless someone else takes over this repo. I would recommend using something more maintained like the project linked above, or switch to letting the Android tooling sign your apps as part of the build (which is the route I've mostly switched to these days, similar to this action you just download your keys and passwords to the build and and let your gradle configuration do the signing). I hit nothing but maintenance issues with this action and have mostly abandoned it.

**Comment by banool** [comment]
Thanks for letting us know!
