### ISSUE TITLE
APK signing failed

### ISSUE THREAD

**Issue by kof5656** [r0adkll/sign-android-release#9]
APK sign's process is two step that is zipalign and sigining

zipalign is success but,
sigining is failed

I see other same issue. but I failed
AAB file is not error

my github secret ```ACTIONS_STEP_DEBUG``` is ```true```
So I can see debug message

My environment : 
- runs-on: windows-latest
- using version: v1
```
Preparing to sign key @ temp with signing key
##[debug]Found release to sign: app-release.apk
##[debug]Zipaligning APK file
##[debug]Found 'zipalign' @ C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\zipalign
...
...
21920372 resources.arsc (OK)
Verification succesful
```
this is success zipalign
no problem

```
##[debug]Signing APK file
##[debug]Found 'apksigner' @ C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\apksigner
"C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\apksigner" sign --ks temp\signingKey.jks --ks-key-alias *** --ks-pass pass:*** --out temp\app-release-signed.apk --key-pass pass:*** temp\app-release-aligned.apk
##[error]There was an error when attempting to execute the process 'C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\apksigner'. This may indicate the process failed to start. Error: spawn C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\apksigner ENOENT
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Sign Release
```
But signing step is not success
I see every issue but I don't know the reason

Other issue is using v1.0.1, so i using too.
But the version is not error but not signing too.

**Comment by IsabellaCaspari** [comment]
same issue here

**Comment by davwheat** [comment]
Try using v1. The action v1 auto-updates, so using v1.0.1 will actually mean you're using an older version. This _should_ be fixed from today.

If you're still having issues, I found this doesn't work correctly on Windows actions, so try switching to Linux.

**Comment by r0adkll** [comment]
@davwheat Is correct (Thanks!). You can update to use `v1` or update to the now latest stable `v1.0.3`
